fastlane_version "2.218.0"

default_platform(:ios)

def get_app_id
  return ENV["APP_IDENTIFIER"] unless ENV["APP_IDENTIFIER"].nil?
  return "ru.artpancreas.***.FreeAPS"
end

def get_team_id
  return ENV["TEAMID"] unless ENV["TEAMID"].nil?
end

platform :ios do
  desc "Fetch certificates and profiles (ONLY MAIN APP)"
  lane :certs do
    match(
      type: "appstore",
      readonly: false,
      app_identifier: get_app_id,
      team_id: get_team_id,
      force: true
    )
  end

  desc "Nuke certificates and profiles"
  lane :nuke_certs do
    match(
      type: "appstore",
      readonly: false,
      app_identifier: get_app_id,
      team_id: get_team_id,
      force: true,
      nuke: true
    )
  end

  desc "Check certificate status"
  lane :check_and_renew_certificates do
    cert_status_file = "#{__dir__}/new_certificate_needed.txt"
    File.write(cert_status_file, "false")
  end

  desc "Build and sign iAPS IPA"
  lane :build_iAPS do
    certs
    build_app(
      scheme: "iAPS",
      export_method: "app-store",
      output_directory: "./artifacts",
      output_name: "iAPS.ipa"
    )
  end

  desc "Upload to TestFlight"
  lane :release do
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end
end
