name: 4. Build iAPS
run-name: Build iAPS (${{ github.ref_name }})

on:
  workflow_dispatch:
  push:

env:
  UPSTREAM_REPO: Artificial-Pancreas/iAPS
  UPSTREAM_BRANCH: ${{ github.ref_name }}
  TARGET_BRANCH: ${{ github.ref_name }}
  ALIVE_BRANCH: alive

jobs:
  auto_build_check:
    name: Check Auto Build Status
    runs-on: ubuntu-latest
    outputs:
      AUTO_BUILD_ENABLED: ${{ steps.auto-build-enabled.outputs.auto_build }}

    steps:
      - name: Is Auto Build Branch
        id: auto-build-enabled
        run: |
          echo "auto_build=true" >> $GITHUB_OUTPUT

      - name: Show Auto Build Status
        run: |
          echo "Auto Build Status: ${{ steps.auto-build-enabled.outputs.auto_build }}"

  build:
    name: Build
    needs: [auto_build_check]
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: Set special variables
        run: |
          if [ ! -z ${{ vars.APP_IDENTIFIER }}  ]; then
            echo "APP_IDENTIFIER=${{ vars.APP_IDENTIFIER }}" >> $GITHUB_ENV
          fi
          if [ ! -z ${{ vars.BUILD_GROUP }}  ]; then
            echo "BUILD_GROUP=${{ vars.BUILD_GROUP }}" >> $GITHUB_ENV
          fi

      - name: Select Xcode version
        run: "sudo xcode-select --switch /Applications/Xcode_26.2.app/Contents/Developer"
      
      - name: Checkout Repo for building
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GH_PAT }}
          submodules: recursive
          ref: ${{ env.TARGET_BRANCH }}

      - name: Install Bundler 2.x
        run: |
          gem install bundler -v 2.7.2
          echo "BUNDLER_VER=2.7.2" >> $GITHUB_ENV

      - name: Patch Match Tables
        run: find /usr/local/lib/ruby/gems -name table_printer.rb | xargs sed -i "" "/puts(Terminal::Table.new(params))/d"

      - name: Install project dependencies
        run: |
          bundle _${{ env.BUNDLER_VER }}_ install

      - name: Build iAPS WITHOUT CERTS
        run: |
          cd ios
          xcodebuild -project iAPS.xcodeproj -scheme iAPS -configuration Release -archivePath build/iAPS archive CODE_SIGNING_ALLOWED=NO
          xcodebuild -exportArchive -archivePath build/iAPS.xcarchive -exportPath build -exportOptionsPlist exportOptions.plist CODE_SIGNING_ALLOWED=NO

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: iAPS-Installer-IPA
          path: ios/build/iAPS.ipa
          retention-days: 7
