name: 4. Build iAPS
run-name: Build iAPS (${{ github.ref_name }})
on:
  workflow_dispatch:
  
  push:
  
env:  
  UPSTREAM_REPO: Artificial-Pancreas/iAPS
  UPSTREAM_BRANCH: ${{ github.ref_name }}
  TARGET_BRANCH: ${{ github.ref_name }}
  ALIVE_BRANCH: alive

jobs:
  auto_build_check:
    name: Check Auto Build Status
    runs-on: ubuntu-latest
    outputs:
      AUTO_BUILD_ENABLED: ${{ steps.auto-build-enabled.outputs.auto_build }}

    steps:
      - name: Is Auto Build Branch
        id: auto-build-enabled
        run: |
          echo "auto_build=true" >> $GITHUB_OUTPUT

      - name: Show Auto Build Status
        run: |
          echo "Auto Build Status: ${{ steps.auto-build-enabled.outputs.auto_build }}"

  # 原来的证书检查直接注释不用，不再运行
  # check_certs: 
  #   needs: auto_build_check
  #   name: Check certificates
  #   if: needs.auto_build_check.outputs.AUTO_BUILD_ENABLED == 'true' || github.event_name == 'workflow_dispatch'
  #   uses: ./.github/workflows/create_certs.yml
  #   secrets: inherit

  # Builds iAPS
  build:
    name: Build
    # 不再依赖证书检查，只依赖前面检测
    needs: [auto_build_check]
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: Set special variables
        run: |
          if [ ! -z ${{ vars.APP_IDENTIFIER }}  ]; then
            echo "APP_IDENTIFIER=${{ vars.APP_IDENTIFIER }}" >> $GITHUB_ENV
          fi
          if [ ! -z ${{ vars.BUILD_GROUP }}  ]; then
            echo "BUILD_GROUP=${{ vars.BUILD_GROUP }}" >> $GITHUB_ENV
          fi

      - name: Select Xcode version
        run: "sudo xcode-select --switch /Applications/Xcode_26.1.1.app/Contents/Developer"
      
      - name: Checkout Repo for building
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GH_PAT }}
          submodules: recursive
          ref: ${{ env.TARGET_BRANCH }}

      - name: Install Bundler 2.x
        run: |
          gem install bundler -v 2.7.2
          echo "BUNDLER_VER=2.7.2" >> $GITHUB_ENV

      - name: Patch Match Tables
        run: find /usr/local/lib/ruby/gems -name table_printer.rb | xargs sed -i "" "/puts(Terminal::Table.new(params))/d"
      
      - name: Install project dependencies
        run: bundle _${{ env.BUNDLER_VER }}_ install

      - name: Sync clock
        run: sudo sntp -sS time.windows.com

      - name: Fastlane Build & Archive
        run: bundle _${{ env.BUNDLER_VER }}_ exec fastlane build_iAPS        
        env:
          TEAMID: ${{ secrets.TEAMID }}
          GH_PAT: ${{ secrets.GH_PAT }}
          FASTLANE_KEY_ID: ${{ secrets.FASTLANE_KEY_ID }}
          FASTLANE_ISSUER_ID: ${{ secrets.FASTLANE_ISSUER_ID }}
          FASTLANE_KEY: ${{ secrets.FASTLANE_KEY }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      
      - name: Fastlane upload to TestFlight
        run: bundle _${{ env.BUNDLER_VER }}_ exec fastlane release
        env:
          TEAMID: ${{ secrets.TEAMID }}
          GH_PAT: ${{ secrets.GH_PAT }}
          FASTLANE_KEY_ID: ${{ secrets.FASTLANE_KEY_ID }}
          FASTLANE_ISSUER_ID: ${{ secrets.FASTLANE_ISSUER_ID }}
          FASTLANE_KEY: ${{ secrets.FASTLANE_KEY }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

      - name: Upload build log, IPA and Symbol artifacts
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: build-artifacts
          path: |
            artifacts
            buildlog
